//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinalRest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public string Id { get; set; }
        public string Nom { get; set; }
        public string Marque { get; set; }
        public Nullable<double> Prix { get; set; }
        public string Categorie { get; set; }
        public string Description { get; set; }
        public string Couleur { get; set; }
        public string Image { get; set; }
        public string SousCategorie { get; set; }
    }
}
