//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetFinalRest.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commandes
    {
        public int Id { get; set; }
        public string IdClient { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Detail { get; set; }
        public Nullable<double> PrixTotal { get; set; }
    }
}
